### ISSUE TITLE
Name of API

### ISSUE THREAD

**Issue by gatha-codeparity** [remiflavien1/mitrecve#1]
Hi

Thanks for the nice work.
Just want to point out that the API name in Readme has been given as: MITRE_get_cve_detail()
Please update it to get_cve_detail()

Cheers!

**Comment by shadawck** [comment]
Thanks, hope it's useful !
Yeah you're right, README have been updated. Change on PyPi will be passed on  the next Pypi release. The main source of documentation remain on [ReadTheDocs](https://mitrecve.readthedocs.io/en/latest/)

**Comment by gatha-codeparity** [comment]
The documentation and package have been very easy to use.
Looking forward to many more cool stuff by you.
