### ISSUE TITLE
Failure to execute

### ISSUE THREAD

**Issue by theslothuk** [remiflavien1/mitrecve#7]
Having followed the install instructions this does not appear to work for me... all I get is the usage prompt below

root@host:~/mitrecve# mitrecve html5lib
usage:
  mitrecve crawl <package> [--verbose --detail ] [--format FORMAT]
  mitrecve show <result>
  mitrecve ( -h | --help | --version )

This, I believe is the command shown in the guide.

Any ideas on how I might troubleshoot please?

**Comment by shadawck** [comment]
Hello @theslothuk
This repo is an old one X). 
I haven't implemented the new version. So the code in the [master] branch was just a WIP (for 2 years).

Thus, I have completed the new version. There is a new package on pypi (mitecve 1.1.1). 
I also added a release tag on github.

**Comment by theslothuk** [comment]
This is so good! I love it.

You must know a lot about mitre and NVD... off topic, but, I wondered if you have any idea of a place I can learn about pulling the nvd zip files into a postgres database or similar, and keeping the whole thing up to date as near as possible real-time. If not thank you so much and you can close this off.

**Comment by shadawck** [comment]
You can look at [cve-search](https://github.com/cve-search/cve-search) and [cve-analysis](https://github.com/joshbressers/cve-analysis) I think.
For CVE monitoring, most of the time I prefer to use Community Edition of professional Tools/Services like Snyk.
